version: '3'

services:

 app:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: simulasi-ci3-app
  working_dir: /var/www
  volumes:
   - ./:/var/www
  depends_on:
   - database
  networks:
   - codeigniter-net

 webserver:
  image: nginx:latest
  container_name: simulasi-ci3-webserver
  volumes:
   - ./:/var/www
   - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - 8084:90
  networks:
   - codeigniter-net

 database:
  image: mysql:5.7
  container_name: simulasi-ci3-db
  ports:
   - 3308:3306
  volumes:
   - mysqldata:/var/lib/mysql
  env_file:
   - .env
  networks:
   - codeigniter-net

 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: simulasi-ci3-pma
  ports:
   - 8085:80
  env_file:
   - .env
  depends_on:
   - database
  networks:
   - codeigniter-net

volumes:
 mysqldata:
  driver: local

networks:
 codeigniter-net:
  driver: bridge
